### ISSUE TITLE
how to open the vein miner options in chat? I opened it accidentally using a keybind?

### ISSUE THREAD

**Issue by waddlinbleach** [oOBoomberOo/veinminer#12]
Please tell me the keybind
![image](https://user-images.githubusercontent.com/97317685/148614216-de86d28d-2115-4782-b73b-525ee244ffe0.png)
d!

**Comment by oOBoomberOo** [comment]
Hi, there is no veinminer option or keybind in this datapack. You are confusing my datapack with someone else.
